In [16]:
import numpy as np

sales = [5,0,155,126,336,227,499]

# vytvoření array
sales_array = np.array(sales)
sales_array

array([  5,   0, 155, 126, 336, 227, 499])

## Základní informace

In [17]:
# NDIM = počet dimenzí
print(f"ndim: {sales_array.ndim}")

# SHAPE = velikost array v každé dimenzi
print(f"shape: {sales_array.shape}")

# SIZE = celkový počet elementů v každé array
print(f"size: {sales_array.size}")

# DTYPE = datový typ v array
print(f"dtype: {sales_array.dtype}")

ndim: 1
shape: (7,)
size: 7
dtype: int32


#### -> nested list - v tomto případě 2 dimenze. Musí mít stejný počet elementů, jinak ERROR

In [18]:
sales_2 = [[5,0,155,126,336,227,499], [35,189,367,611,239,444,10]]

sales_array_2 = np.array(sales_2)
sales_array_2

array([[  5,   0, 155, 126, 336, 227, 499],
       [ 35, 189, 367, 611, 239, 444,  10]])

In [19]:
# NDIM = počet dimenzí
print(f"ndim: {sales_array_2.ndim}")

# SHAPE = velikost array v každé dimenzi -> 2 dimenze po 7 elementech
print(f"shape: {sales_array_2.shape}")

# SIZE = celkový počet elementů v každé array
print(f"size: {sales_array_2.size}")

# DTYPE = datový typ v array
print(f"dtype: {sales_array_2.dtype}")

ndim: 2
shape: (2, 7)
size: 14
dtype: int32


In [24]:
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [26]:
array_2 = np.array([range(5), range(5)])
array_2

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [30]:
# TRANSPOZICE array
array_2.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])